# Generated by Django 4.0.10 on 2024-02-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='project_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
