# Generated by Django 4.0.10 on 2024-02-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_projectmodel_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_filemodel_project_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.projectmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
