# Generated by Django 4.0.10 on 2024-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField()),
                ('project_ref', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
