# Generated by Django 4.0.10 on 2024-02-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_projectmodel_cost'),
        ('core', '0005_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('proj_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.projectmodel')),
            ],
        ),
    ]
