# Generated by Django 4.0.10 on 2024-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='va',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='vp',
            field=models.IntegerField(default=0),
        ),
    ]
