# Generated by Django 4.0.10 on 2024-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('reception', models.IntegerField()),
                ('engagement', models.CharField(max_length=20)),
                ('fournisseur', models.CharField(max_length=20)),
                ('shipment_num', models.CharField(max_length=10, null=True)),
                ('devise', models.CharField(max_length=10)),
                ('receptionnaire', models.CharField(max_length=20)),
                ('mt_engagement', models.FloatField()),
                ('objet', models.CharField(max_length=20)),
                ('mt_reception', models.FloatField()),
            ],
        ),
    ]
