# Generated by Django 4.0.10 on 2024-02-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('phase_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.phase')),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.project')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='project_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.project'),
        ),
    ]
