# Generated by Django 4.0.10 on 2024-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_phasemodel_projectmodel_taskmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
