# Generated by Django 4.0.10 on 2024-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_projectmodel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
